### ISSUE TITLE
[scss] extra min-width in media query

### ISSUE THREAD

**Issue by zebapy** [middlebury/midd-frontend#251]
Some styles are getting generated as below.

```scss
@media only screen and (min-width: 768px) and (min-width: 1024px) {
  .stat-panel__content {
    margin-right: -2rem;
    margin-left: -2rem;
  }
  .stat-panel__item {
    padding-right: 2rem;
    padding-left: 2rem;
  }
}
```

The extra min-width (smaller size) does nothing. 

Expected result would be only the larger min-width.
```scss
@media only screen and (min-width: 1024px) {
```
