### ISSUE TITLE
consider removing animations if prefers-reduced-motion is on

### ISSUE THREAD

**Issue by zebapy** [middlebury/midd-frontend#311]
https://github.com/jensimmons/cssremedy/blob/master/css/reminders.css#L39
```css
@media (prefers-reduced-motion: reduce) {
  *, ::before, ::after {
    animation-delay: -1ms !important;
    animation-duration: 1ms !important;
    animation-iteration-count: 1 !important;
    background-attachment: initial !important;
    scroll-behavior: auto !important;
    transition-delay: 0s !important;
    transition-duration: 0s !important;
  }
}
```
